### ISSUE TITLE
push_service.rb:47: syntax error, unexpected ':', expecting =>  "tokens": @device_tokens,

### ISSUE THREAD

**Issue by edemkumodzi** [nwwatson/ionic_push#1]
I just tried installing the gem and when i ran the "bundle exec rails g ionic_push:install" command, i got this error. I initially thought maybe the command had an issue but even when running rails console I get the same error. I noticed that you did some refactorings 4 days ago, could that have created this issue?

**Comment by nwwatson** [comment]
@edemkumodzi, I think you may have an older version the gem. To update, do:

```
bundle update ionic_push
```

The API was changed a bit when I refactored. Sending a generic alert could have been done by calling notify! This has changed. you can send the exact same message by doing:

``` ruby
service = IonicPush::PushService.new(device_tokens: device_tokens)
service.alert!("Is this you John Wayne? Is this me?")
```

If you need to customize your message more, you can supply a block to the notify method:

``` ruby
service = IonicPush::PushService.new(device_tokens: device_token)
service.notify do
  {
    "alert":"You've got updated messages!",
    "android":{
      "title":"Updated Messages",
      "payload":{
        "type":"configuration"
      }
    }
  }
end
```

Hope this helps a bit. We have this running on a live app without issue.

**Comment by edemkumodzi** [comment]
Still doesn't work.
What's the latest version I need to install? What I have is 0.0.1

**Comment by nwwatson** [comment]
What version of ruby are you using?

If you look at your Gemfile.lock, you should have an entry like this:

```
GIT
  remote: git://github.com/nwwatson/ionic_push.git
  revision: 38a172eb46576cce72dd0c80033a173ea2ab037c
  branch: master
  specs:
    ionic_push (0.0.2)
      httparty (~> 0.13.5)
      rails (~> 4.2.1)
```

**Comment by edemkumodzi** [comment]
Using Ruby 2.2.0-preview

**Comment by edemkumodzi** [comment]
I get the exact same entry you have. I don't know if it makes any difference but I'm using rails-api, not the full rails. Could there be another dependency that's missing?

**Comment by nwwatson** [comment]
@edemkumodzi Try updating. It looks like the preview version of ruby didn't like the hash syntax I was using. I tested it and you should be good to go.

New version is 0.0.3
